language: rust
rust:
    - nightly
before_script:
    - rustup component add rustfmt-preview
    - cargo install clippy
script:
    - cargo fmt --all -- --check
    - cargo build
    - cargo test
    - cargo clippy
