[package]
name = "checkco"
version = "0.1.0"
authors = ["Paul Loyd <pavelko95@gmail.com>"]

[dependencies]
serde_json = "1.0.22"
serde = { version = "1.0.70", features = ["rc"]}
serde_derive = "1.0.70"
either = "1.5.0"
itertools = "0.7.8"
structopt = "0.2.10"
